version: '3.1'

services:

  db:
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: password
      POSTGRES_DB: ossound
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
