services:
  app:
    depends_on:
      postgres-test:
        condition: service_healthy
    build:
      context: '.'
      dockerfile: 'Dockerfile'
      target: test
    environment:
      POSTGRES_URL: postgresql://user:password@postgres-test/ossound-test
      JWT_SECRET: HLJLSWIXUKAWOBREWREKUYAKOKOCHIYI
    volumes:
      - ./:/usr/app
    # command: sh -c "npm run migrations:run && node --test --watch --require ts-node/register ./test/user/user.test.ts"

  postgres-test:
    image: 'postgres:15-alpine'
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: ossound-test
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d ossound-test']
      interval: 5s
      timeout: 5s
      retries: 5
