services:
  postgres:
    image: 'postgres:15-alpine'
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: ossound
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d ossound']
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: '.'
      dockerfile: 'Dockerfile'
      target: dev
    ports:
      - '8080:3000'
    volumes:
      - ./:/usr/app
    environment:
      POSTGRES_URL: postgresql://user:password@postgres/ossound
      JWT_SECRET: HLJLSWIXUKAWOBREWREKUYAKOKOCHIYI

  adminer:
    depends_on:
      - postgres
    image: adminer
    restart: always
    ports:
      - 8081:8080
